import React,{useState,useEffect,useRef} from 'react';
import {request,useStore,refresh,submitOnce,pendingOperation} from '../store';
import {Modal} from '../components';
import {money} from '../domain';
function Editor({item,kind,data,onClose,onSaved}) {
 const category=kind==='categories',scope='new-catalog-'+kind;
 const pending=!item?.id&&pendingOperation(scope);
 const [value,setValue]=useState(pending?.body||item||{name:'',description:'',categoryId:data.categories[0]?.id||'',price:'',image:'',available:true,visible:true,order:0,note:''});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[uncertain,setUncertain]=useState(!!pending);const lock=useRef(false);const s=useStore();
 const change=(key,v)=>setValue(old=>({...old,[key]:v}));
 return <Modal title={(item?.id?'Editar ':'Nueva alta de ')+(category?'categoría':'producto')} onClose={()=>{if(!busy&&!uncertain)onClose();}}><form onSubmit={async e=>{e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');const body=category?{name:value.name,image:value.image||null,order:Number(value.order),visible:value.visible,note:value.note||''}:{name:value.name,description:value.description||'',categoryId:value.categoryId,price:value.price===''||value.price==null?null:value.price,image:value.image||null,available:value.available};try{if(item?.id)await request('/menu-management/'+kind+'/'+item.id,{method:'PUT',body});else await submitOnce(scope,'/menu-management/'+kind,body);setUncertain(false);onSaved();}catch(e){setError(e.message);setUncertain(!!e.uncertain);}finally{lock.current=false;setBusy(false);}}}>
 <fieldset disabled={busy||uncertain} className="catalog-fields"><label>Nombre<input required maxLength={category?100:150} value={value.name} onChange={e=>change('name',e.target.value)}/></label>
 {category?<><label>Orden en la carta<input required type="number" min="0" max="9999" value={value.order} onChange={e=>change('order',e.target.value)}/></label><label>Nota para clientes<textarea maxLength={500} value={value.note||''} onChange={e=>change('note',e.target.value)}/></label><label className="option"><input type="checkbox" checked={value.visible} onChange={e=>change('visible',e.target.checked)}/>Mostrar categoría en la carta pública</label><small>Ocultarla conserva sus productos para atención.</small></>:<><label>Categoría<select required value={value.categoryId} onChange={e=>change('categoryId',e.target.value)}><option value="">Elegir categoría</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Precio de venta ($) · opcional<input type="number" min="0" step="0.01" max="9999999999.99" value={value.price??''} onChange={e=>change('price',e.target.value)} placeholder="Sin precio definido"/></label><small>Sin precio: muestra “Consultar precio” y no se puede vender desde atención. Los precios anteriores de los pedidos no cambian.</small><label>Descripción<textarea maxLength={500} value={value.description||''} onChange={e=>change('description',e.target.value)}/></label><label className="option"><input type="checkbox" checked={value.available} onChange={e=>change('available',e.target.checked)}/>Habilitar venta (sujeta a precio y stock)</label></>}
 <label>Foto<select value={value.image||''} onChange={e=>change('image',e.target.value)}><option value="">Sin foto</option>{[...new Set([...data.images,...(value.image?[value.image]:[])])].map(src=><option key={src} value={src}>{src.split('/').pop()}</option>)}</select></label><small>Las fotos se cargan en frontend/public/menu. Se conservan las opciones, sabores y vínculos de stock existentes al editar.</small></fieldset>
 {error&&<p className="alert" role="alert">{error}</p>}{uncertain&&<p className="note">La respuesta no se confirmó. Reintentá el mismo guardado antes de cerrar.</p>}<button className="primary full" disabled={busy||!s.connected}>{busy?'Guardando…':uncertain?'Reintentar guardado':'Guardar cambios'}</button></form></Modal>;
}
export default function MenuManagement(){const [data,setData]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState(''),[tab,setTab]=useState('products'),[archived,setArchived]=useState(false),[editor,setEditor]=useState(null),[remove,setRemove]=useState(null),[busy,setBusy]=useState(false);const lock=useRef(false);const s=useStore();
 async function load(){try{setData(await request('/menu-management'));setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{void load();},[]);
 async function saved(){setEditor(null);setRemove(null);setMessage('Cambios guardados. La carta se actualizará automáticamente.');await load();await refresh();}
 async function retire(p,restore=false){if(lock.current)return;lock.current=true;setBusy(true);try{await request('/menu-management/products/'+p.id+(restore?'/restore':''),{method:restore?'POST':'DELETE'});await saved();}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 return <main className="catalog-admin"><div className="page-heading"><div><h1>Gestionar carta</h1><p>Productos, precios y categorías de NaniFer.</p></div><div className="catalog-actions"><button className="primary" disabled={!data||!s.connected} onClick={()=>setEditor({kind:'products'})}>+ Nuevo producto</button><button className="secondary" disabled={!data||!s.connected} onClick={()=>setEditor({kind:'categories'})}>+ Nueva categoría</button></div></div>
 {error&&<p className="alert" role="alert">{error}<button onClick={load}>Reintentar</button></p>}{message&&<p className="success" role="status">{message}</p>}{!data&&!error&&<p role="status">Cargando carta…</p>}{data&&<><div className="catalog-actions"><button className={tab==='products'?'primary':'secondary'} onClick={()=>setTab('products')}>Productos</button><button className={tab==='categories'?'primary':'secondary'} onClick={()=>setTab('categories')}>Categorías</button></div><div className="stock-filters"><label>Buscar<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre del producto o categoría"/></label>{tab==='products'&&<><label>Categoría<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="option"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Ver retirados</label></>}</div>
 <div className="catalog-list">{data[tab].filter(p=>p.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())&&(tab==='categories'||(p.archived===archived&&(!filter||p.categoryId===filter)))).map(p=><article className="panel catalog-row" key={p.id}><div><h2>{p.name}</h2>{tab==='products'?<><strong>{p.price==null?'Consultar precio':money(p.price)}</strong><p>{data.categories.find(c=>c.id===p.categoryId)?.name} · {p.archived?'Retirado':!p.available?'Venta deshabilitada':p.price==null?'Precio pendiente':'Habilitado según stock'}</p>{p.description&&<p>{p.description}</p>}</>:<p>Orden {p.order} · {p.visible?'Visible en la carta':'Oculta al público'}</p>}</div><div className="catalog-actions"><button className="secondary" disabled={!s.connected||busy} onClick={()=>setEditor({kind:tab,item:p})}>Editar</button>{tab==='products'&&(p.archived?<button className="secondary" disabled={busy||!s.connected} onClick={()=>retire(p,true)}>Restaurar</button>:<button className="text-button" disabled={busy||!s.connected} onClick={()=>setRemove(p)}>Retirar de la carta</button>)}</div></article>)}</div>{!data[tab].some(p=>p.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())&&(tab==='categories'||(p.archived===archived&&(!filter||p.categoryId===filter))))&&<p>No hay resultados para estos filtros.</p>}
 {['products','categories'].map(kind=>pendingOperation('new-catalog-'+kind)&&<p className="note" key={kind}>Hay un alta pendiente de confirmación. <button onClick={()=>setEditor({kind})}>Recuperar guardado</button></p>)}</>}
 {editor&&<Editor {...editor} data={data} onClose={()=>setEditor(null)} onSaved={saved}/>}{remove&&<Modal title="Retirar producto" onClose={()=>!busy&&setRemove(null)}><p>¿Retirar {remove.name} de la carta y de nuevas ventas? Sus consumos, stock e historial se conservan. Podés restaurarlo después.</p><button className="primary full" disabled={busy||!s.connected} onClick={()=>retire(remove)}>{busy?'Guardando…':'Confirmar retiro'}</button></Modal>}</main>;
}
